apiVersion: v1
kind: Pod
metadata:
  name: job1
spec:
  containers:
  - args:
    - app.py
    - '200'
    - /root/job1.csv
    - job1
    command:
    - python
    image: fuyuqi1995/mig-lenet
    name: lenet-test-epoch
  restartPolicy: Never
