apiVersion: v1
kind: PersistentVolume
metadata:
  name:  task-pv-volumn
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /mnt/linuxidc/
    server: 128.110.153.146
